# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-22 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_post_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
